package main

import "github.com/kataras/iris"

func main() {
	iris.Get("/:version/apps", testJSON)
	iris.Post("/:version/apps", testJSON)
	iris.Delete("/:version/apps/:AppId", testJSON)
	iris.Delete("/:version/apps/:AppId/recover", testJSON)
	iris.Post("/:version/apps/clean/", testJSON)
	iris.Get("/:version/apps/:AppId/reset", testJSON)
	iris.Post("/:version/apps/production/", testJSON)
	iris.Put("/:version/apps/:AppId/key", testJSON)
	iris.Get("/:version/schemas/", testJSON)
	iris.Get("/:version/schemas/:collection", testJSON)
	iris.Post("/:version/schemas/:collection", testJSON)
	iris.Delete("/:version/schemas/:collection", testJSON)
	iris.Put("/:version/schemas/:collection", testJSON)
	iris.Post("/:version/batch", testJSON)
	iris.Post("/:version/jobs", testJSON)
	iris.Get("/:version/jobs", testJSON)
	iris.Get("/:version/jobs/:AppId", testJSON)
	iris.Put("/:version/jobs/:id", testJSON)
	iris.Delete("/:version/jobs/:id", testJSON)
	iris.Patch("/:version/jobs/:id", testJSON)
	iris.Patch("/:version/jobs/", testJSON)
	iris.Post("/:version/classes/:collection", testJSON)
	iris.Get("/:version/classes/:collection/:id", testJSON)
	iris.Get("/:version/classes/:collection", testJSON)
	iris.Put("/:version/classes/:collection/:id", testJSON)
	iris.Patch("/:version/classes/:collection/:id", testJSON)
	iris.Delete("/:version/classes/:collection/:id", testJSON)
	iris.Patch("/:version/classes/:collection", testJSON)
	iris.Delete("/:version/classes/:collection", testJSON)
	iris.Get("/:version/passwords/:user", testJSON)
	iris.Put("/:version/passwords/:user", testJSON)
	iris.Delete("/:version/passwords/:user", testJSON)
	iris.Get("/:version/groups/:group", testJSON)
	iris.Put("/:version/groups/:group", testJSON)
	iris.Delete("/:version/groups/:group", testJSON)
	iris.Post("/:version/archives/classes/:collection", testJSON)
	iris.Get("/:version/archives/classes/:collection", testJSON)
	iris.Delete("/:version/archives/classes/:collection/", testJSON)
	iris.Post("/:version/echo/:collection", testJSON)
	iris.Get("/:version/echo/:collection", testJSON)
	iris.Get("/:version/echo/:collection/:id", testJSON)
	iris.Put("/:version/echo/:collection/:id", testJSON)
	iris.Delete("/:version/echo/:collection/:id", testJSON)
	iris.Get("/:version/ping", testJSON)
	iris.Get("/:version/checkmongos", testJSON)
	iris.Get("/:version/version", testJSON)
	iris.Get("/:version/config", testJSON)
	iris.Get("/:version/clean", testJSON)
	iris.Get("/:version/init", testJSON)
	iris.Get("/:version/cache", testJSON)
	iris.Get("/:version/goinfo", testJSON)
	iris.Get("/:version/kill", testJSON)
	iris.Get("/:version/pfinsert", testJSON)
	iris.Get("/:version/pfread", testJSON)
	iris.Get("/:version/checkindex", testJSON)
	iris.Listen(":8888")
}

func testJSON(c *iris.Context) {
	json := map[string]int{"Code": 0}
	c.JSON(iris.StatusOK, json)
}
